version: "3"
services:
  app:
    build: ./
    container_name: app
    volumes:
      - ./server:/srv/app/manpower-server
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - PORT=3000
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
